#! /bin/bash

# WARNING: Outside the context of an automated test, the following instruction
# is a security hole! NEVER DO THIS outside a well-controlled environment!
# You have been warned.
# See http://www.faqs.org/faqs/unix-faq/faq/part2/section-13.html
# See also http://superuser.com/questions/944973
PATH="$PATH:."

$1 -- -h
